
task1:
  move_to_pick:
    group: arm_torso
    joints: [1.57, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  close_gripper:
    group: gripper
    joints: [0.04, 0.04]
  pre_grasp:
    group: arm
    joints: [2.58, 0.37, 1.07, 1.27, -1.69, 1.36, -1.31]
  grasp:
    group: arm
    joints: [2.32, -0.52, 1.06, 0.86, -1.24, 1.12, 2.08]
  close_gripper:
    group: gripper
    joints: [0.04, 0.04]
  post_grasp:
    group: arm
    joints: [2.32, -0.77, 1.48, 1.22, -1.03, 0.96, 2.08]
  open_gripper:
    group: gripper
    joints: [0.04, 0.04]
  # move_to_place:
  #   group: arm
  #   joints: [1.57, -0.5, 0.0, 1.3, 0.0, 0.0, 0.0]
  # close_gripper:
  #   group: gripper
  #   joints: [0.0, 0.0]
  # post_grasp:
  #   group: arm
  #   joints: [2.32, -0.08, 1.06, 0.86, -1.24, 1.1, 1.06]
  # move_home:
  #   group: arm_torso
  #   joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
